acme_lists:
    resource: "@AcmeListsBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
    prefix:   /

